site_name: Accident AI Docs

nav:
  - 'index.md'
  - Setup: pages/setup.md
  - Users: pages/users.md
  - Cases: pages/cases.md
  - Api Keys: pages/api-keys.md
  - About: pages/about.md
  - License: pages/license.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name: material
  palette:
    primary: green
  features:
    - navigation.instant
    - navigation.tracking


extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/squidfunk
    - icon: fontawesome/brands/facebook 
      link: https://twitter.com/squidfunk
    - icon: fontawesome/brands/google 
      link: https://twitter.com/squidfunk
  generator: false

